# Generated by Django 3.1.3 on 2020-11-20 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='book_discription',
            field=models.TextField(max_length=200),
        ),
    ]
